---

fail_fast: false

repos:

  - repo: https://github.com/adrienverge/yamllint.git
    sha: v1.11.0
    hooks:
      - id: yamllint
        args: ['--format', 'parsable', '--strict']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: detect-private-key

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.4
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    sha: 1.5.1
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            assets/docker_hub_workflow.png
          )$
      - id: git-check  # Configure in .gitattributes
      - id: git-dirty  # Configure in .gitignore
      - id: shellcheck
      - id: shfmt
